### ISSUE TITLE
Start a new chat&conversation in Admin GUI

### ISSUE THREAD

**Issue by KevinZhang19870314** [cheshire-cat-ai/widget-vue#1]
It would be wonderful that we can have a button to start a new chat in GUI.
I found that even I refresh the http://localhost:3000 page, the `chat_history` is still in current conversation, but I just want a new chat, I don't need previous chat context.

a workround is to `docker-compose down` and `docker-compose up`, then we can have a fresh chat, but obviously it is not really good method to start a new chat yet.

**Comment by pieroit** [comment]
@KevinZhang19870314 this is a good idea and must be implemented, as soon as we reach agreement on cheshire-cat-ai/core#169 and cheshire-cat-ai/core#62 
Hope you can read there (#169 ) and leave your view on how to proceed

**Comment by cristianorevil** [comment]
Please assign to me

**Comment by pieroit** [comment]
Let's decompose this in two steps:

1. endpoint DELETE `/memory/working-memory/conversation-history`
2. add reset conversation in admin

**Comment by zAlweNy26** [comment]
@pieroit should the reset button be in the chat view or in the settings?

**Comment by pieroit** [comment]
@zAlweNy26 let's put the button in the chat toolbar as this is much requested

It also could have a place in the memory view (in the future)

Before coding it let's redesign the chat wireframe a little

**Comment by pieroit** [comment]
@KevinZhang19870314 there is now an endpoint in core to reset conversation:

```
DELETE /working-memory/conversation-history/
```

We are redesigning a little the chat widget to also have a button for the endpoint.
Are you good at design?

**Comment by pieroit** [comment]
@cristianorevil thanks for adding the endpoint.  
I moved the issue to the widget repo to add a button for the endpoint

**Comment by zAlweNy26** [comment]
@pieroit I added a temporary button just to use the endpoint, we can obviously discuss the current implementation and change it. 

![image](https://github.com/cheshire-cat-ai/widget-vue/assets/41266342/bb445719-25a4-44e5-b557-f646bf1fc1db)

**Comment by pieroit** [comment]
Looks good!

Near the input box let's have the clear button after or before the upload, but for sure after the send button

 (buttons ordered from more frequently used to less frequently used

**Comment by zAlweNy26** [comment]
> Looks good!
> 
> Near the input box let's have the clear button after or before the upload, but for sure after the send button
> 
> (buttons ordered from more frequently used to less frequently used

But then there will be 3 buttons inside the input box, decreasing the space for the text

**Comment by pieroit** [comment]
Let's wireframe
